var colorList = [
  {"id": 384, "name": "WHITE", "listOrder": 1, "renderName": "흰색"},
  {"id": 385, "name": "GREY", "listOrder": 2, "renderName": "회색"},
  {"id": 386, "name": "CHARCOAL", "listOrder": 3, "renderName": "챠콜색"},
  {"id": 387, "name": "BLACK", "listOrder": 4, "renderName": "검정색"},
  {"id": 378, "name": "IVORY", "listOrder": 5, "renderName": "아이보리색"},
  {"id": 379, "name": "BEIGE", "listOrder": 6, "renderName": "베이지색"},
  {"id": 373, "name": "SKY BLUE", "listOrder": 7, "renderName": "하늘색"},
  {"id": 374, "name": "BLUE", "listOrder": 8, "renderName": "파랑색"},
  {"id": 375, "name": "NAVY", "listOrder": 9, "renderName": "남색"},
  {"id": 381, "name": "BROWN", "listOrder": 10, "renderName": "갈색"},
  {"id": 380, "name": "CAMEL", "listOrder": 11, "renderName": "카멜색"},
  {"id": 382, "name": "WINE", "listOrder": 12, "renderName": "와인색"},
  {"id": 383, "name": "KHAKI", "listOrder": 13, "renderName": "카키색"},
  {"id": 367, "name": "LIGHT PINK", "listOrder": 14, "renderName": "밝은 분홍"},
  {"id": 368, "name": "PINK", "listOrder": 15, "renderName": "분홍색"},
  {"id": 364, "name": "RED", "listOrder": 16, "renderName": "빨강색"},
  {"id": 365, "name": "ORANGE", "listOrder": 17, "renderName": "주황색"},
  {"id": 366, "name": "SALMON", "listOrder": 18, "renderName": "연어색"},
  {"id": 369, "name": "YELLOW", "listOrder": 19, "renderName": "노랑색"},
  {"id": 376, "name": "LAVENDER", "listOrder": 20, "renderName": "라벤다"},
  {"id": 377, "name": "PURPLE", "listOrder": 21, "renderName": "보라색"},
  {"id": 370, "name": "MINT", "listOrder": 22, "renderName": "민트색"},
  {"id": 371, "name": "LIGHT GREEN", "listOrder": 23, "renderName": "밝은 녹색"},
  {"id": 372, "name": "GREEN", "listOrder": 24, "renderName": "녹색"},
  {"id": 388, "name": "SILVER", "listOrder": 25, "renderName": "은색"},
  {"id": 389, "name": "GOLD", "listOrder": 26, "renderName": "금색"}
];
